
version: '3'

services:

  pg:
    build: ./pg
    container_name: pg
    ports:
      - "5432:5432"

  node:
    build: ./nodejs
    container_name: node
    ports:
      - "3001:3001"
    depends_on:
      - pg

  front:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - pg



